language: python
python:
  - '3.9.2'
  - '3.10-dev'
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
  - pip install pytest-cov codecov
script:
  - pytest --cov=cs --cov-report= --durations=0
after_success:
  - codecov
